data_source snowflake_db:
  type: snowflake
  connection:
    username: Janardhanreddy
    password: Prasanna@0724
    account: tv75323.central-india.azure
    database: AIRFLOW_TUTORIAL_DB
    warehouse: COMPUTE_WH
    role: ACCOUNTADMIN
    client_session_keep_alive: true
    session_parameters:
      QUERY_TAG: soda-queries
      QUOTED_IDENTIFIERS_IGNORE_CASE: false
    schema: AIRFLOW_TUTORIAL_SCHEMA
soda_cloud:
  host: cloud.soda.io
  api_key_id: 541a5d47-d9de-4c50-b670-c9befe01575e
  api_key_secret: YnORUwDzpqsVxSU5by0Ayl4kAabiwRFd1303kNvAixgqn3cWlDgkmw
