data_source dbsource:  
    type: snowflake
    account: dx24402.ap-south-1.aws
    username: Prasanna2411
    password: ANJI@14322p
    role: accountadmin
    database: SNOWFLAKE_SAMPLE_DATA
    warehouse: compute_wh
    schema:   TPCH_SF1000
    threads: 10
    client_session_keep_alive: False


soda_cloud:
  host: cloud.soda.io
  api_key_id: 541a5d47-d9de-4c50-b670-c9befe01575e
  api_key_secret: YnORUwDzpqsVxSU5by0Ayl4kAabiwRFd1303kNvAixgqn3cWlDgkmw
